/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-113561-ge05d3c1a16-20240207"
#endif /* AVUTIL_FFVERSION_H */
